### ISSUE TITLE
[Docs][UX] Users struggle to install initial dependencies

### ISSUE THREAD

**Issue by skandermoalla** [CLAIRE-Labo/python-ml-research-template#12]
Users may think they have to put their additional dependencies in the `requirements.txt`/`environment.yml`/`Dockerfile` before they build for the first time.
However, its likely that their additional dependencies have some sort of installation issues, which they will have to solve through iterative builds.
It would be better to guide them towards building with the default dependencies first, then installing their dependencies while developing on a running container to understand their challenges, then finally at the end transcribe their install steps in the dependency files.

**Comment by skandermoalla** [comment]
@andreamiele

**Comment by skandermoalla** [comment]
@Pompey21

**Comment by Pompey21** [comment]
Hi, yes I agree! I don't mind writing that up if it helps :) (@skandermoalla )

**Comment by skandermoalla** [comment]
Yes, please! @Pompey21
